import Link from "next/link";
import { Zap, ArrowLeft } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background">
            <nav className="border-b border-border">
                <div className="max-w-3xl mx-auto px-4 h-16 flex items-center justify-between">
                    <Link href="/" className="flex items-center gap-2">
                        <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
                            <Zap className="w-5 h-5 text-white" />
                        </div>
                        <span className="font-bold text-lg">AdMaster Pro</span>
                    </Link>
                    <Link href="/" className="text-sm text-muted hover:text-foreground flex items-center gap-1">
                        <ArrowLeft className="w-4 h-4" /> Back
                    </Link>
                </div>
            </nav>

            <main className="max-w-3xl mx-auto px-4 py-12">
                <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
                <div className="prose prose-sm dark:prose-invert space-y-4 text-muted">
                    <p><strong>Last updated:</strong> January 2025</p>

                    <h2 className="text-lg font-semibold text-foreground mt-8">1. Service Description</h2>
                    <p>AdMaster Pro is an AI-powered Google Ads management platform. We provide campaign analysis, ad copy generation, keyword recommendations, and optimization tools.</p>

                    <h2 className="text-lg font-semibold text-foreground mt-8">2. Account Requirements</h2>
                    <p>You must be at least 18 years old to use this service. You are responsible for maintaining the security of your account credentials.</p>

                    <h2 className="text-lg font-semibold text-foreground mt-8">3. Google Ads Integration</h2>
                    <p>By connecting your Google Ads account, you authorize AdMaster Pro to read your campaign data and, with your explicit approval, make changes to your campaigns. You retain full ownership and control of your Google Ads account at all times.</p>

                    <h2 className="text-lg font-semibold text-foreground mt-8">4. AI-Generated Content</h2>
                    <p>Ad copy and recommendations are generated by AI. While we strive for accuracy, you are responsible for reviewing all AI-generated content before publishing it. We recommend verifying compliance with Google Ads policies.</p>

                    <h2 className="text-lg font-semibold text-foreground mt-8">5. Subscriptions & Billing</h2>
                    <p>Paid plans are billed monthly through Stripe. You can cancel at any time — your plan continues until the end of the current billing period. Top-up message credits never expire.</p>

                    <h2 className="text-lg font-semibold text-foreground mt-8">6. Limitation of Liability</h2>
                    <p>AdMaster Pro is not responsible for the performance of your Google Ads campaigns. We provide tools and recommendations, but actual ad performance depends on many factors including your budget, market conditions, and ad quality.</p>

                    <h2 className="text-lg font-semibold text-foreground mt-8">7. Modifications</h2>
                    <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms.</p>

                    <h2 className="text-lg font-semibold text-foreground mt-8">8. Contact</h2>
                    <p>For questions about these terms, contact us at <a href="mailto:support@admasterai.com" className="text-primary hover:underline">support@admasterai.com</a>.</p>
                </div>
            </main>
        </div>
    );
}
